// Code generated by wit-bindgen-go. DO NOT EDIT.

//go:build !wasip1

// Package stdin represents the imported interface "wasi:cli/stdin@0.2.0".
package stdin

import (
	"github.com/rajatjindal/wasip2-http-incoming-handler/wasi/io/streams"
)

// GetStdin represents the imported function "get-stdin".
//
//	get-stdin: func() -> input-stream
//
//go:nosplit
func GetStdin() streams.InputStream {
	return wasmimport_GetStdin()
}

//go:wasmimport wasi:cli/stdin@0.2.0 get-stdin
//go:noescape
func wasmimport_GetStdin() streams.InputStream
