// Code generated by wit-bindgen-go. DO NOT EDIT.

//go:build !wasip1

// Package instancenetwork represents the imported interface "wasi:sockets/instance-network@0.2.0".
//
// This interface provides a value-export of the default network handle..
package instancenetwork

import (
	"github.com/rajatjindal/wasip2-http-incoming-handler/wasi/sockets/network"
)

// InstanceNetwork represents the imported function "instance-network".
//
// Get a handle to the default network.
//
//	instance-network: func() -> network
//
//go:nosplit
func InstanceNetwork() network.Network {
	return wasmimport_InstanceNetwork()
}

//go:wasmimport wasi:sockets/instance-network@0.2.0 instance-network
//go:noescape
func wasmimport_InstanceNetwork() network.Network
