// Code generated by wit-bindgen-go. DO NOT EDIT.

//go:build !wasip1

// Package stdout represents the imported interface "wasi:cli/stdout@0.2.0".
package stdout

import (
	"github.com/rajatjindal/wasip2-http-incoming-handler/wasi/io/streams"
)

// GetStdout represents the imported function "get-stdout".
//
//	get-stdout: func() -> output-stream
//
//go:nosplit
func GetStdout() streams.OutputStream {
	return wasmimport_GetStdout()
}

//go:wasmimport wasi:cli/stdout@0.2.0 get-stdout
//go:noescape
func wasmimport_GetStdout() streams.OutputStream
